# Generated by Django 5.0.6 on 2024-05-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0004_actor_rename_name_movie_title_alter_movie_footage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='title',
        ),
    ]
