# Generated by Django 5.0.6 on 2024-05-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0005_rename_name_genre_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='name',
            new_name='title',
        ),
    ]
