# Generated by Django 5.0.3 on 2024-05-24 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0007_movie_actors_movie_director_movie_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='title',
            new_name='name',
        ),
    ]
