# Generated by Django 5.0.6 on 2024-05-30 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0008_rename_title_actor_name_rename_title_director_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='name',
        ),
    ]
